spring.application.name=CRUD-LIBRARY

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:book
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=samuel
spring.datasource.password=p@55w0rD

server.port=8080